### 🔗 SHAREPOINT CONFIG
SHAREPOINT_SITE_URL = "https://data03.sharepoint.com/sites/WorkforceProjectReporting"
DOCUMENT_LIBRARY = "PowerBI_Equans_Data"
UPLOAD_FOLDER = "Live_Logs"

### 📂 FILE PATHS
DATA_LOG_CSV = "data_log.csv"

# Department Labels
DEPARTMENT_COLUMNS = ['ARCHITECTURAL', 'COMMERCIAL', 'COMMISSIONING', 'CONSULTING', 'DATA & SECURITY', 'DESIGN MANAGEMENT',
                      'DEVELOPMENT', 'DOCUMENT CONTROL', 'ELECTRICAL', 'ESTIMATING', 'INDUSTRIAL MAINTENANCE', 'MANAGEMENT',
                      'MANAGEMENT & ADMIN', 'MANAGEMENT ACCOUNTS', 'MECHANICAL', 'OPERATIVE', 'PLANNING', 'PROCESS', 'PROCUREMENT',
                      'PROJECT MANAGEMENT', 'QUALITY, SAFETY & ENVIRONMENT', 'SERVICES', 'TECHNICAL', 'VALIDATION & REGULATORY AFFAIRS']

